### PR TITLE
Issue 471 database query name usages

### LINKED ISSUE #471: Maximize use of internal IDs in queries to minimize effects of changing names (e.g. traits)

### LINKED ISSUE #914: BUG: Breedbase my export fails with the error "Response number of observations different from request"
### Description

When I try to import my traits from Breedbase onto Fieldbook v5.6 I am only given the options to use Local or Cloud storage making me unable to import my traits from Breedbase using BrAPI. 
Screenshot_20240312-155207
Also when trying to export new observations via BrAPI back to Breedbase my export fails with the error "Response number of observations different from request".  
Screenshot_20240312-155843

These errors do not occur when using v5.5

### Expected behavior

_No response_

### Field Book version

5.6.8

### LINKED ISSUE #981: [BUG]: Renaming trait breaks linkage to existing phenotypes
### Description

When exporting trait data, one set of data was exported only partially. It was categorical data and only 15 entries of about 100 was present in the csv file. Within the app the data is recorded. 

### Expected behavior

_No response_

### Field Book version

5.5.24

### LINKED ISSUE #1281: [BUG]: Error when Exporting collected data to BMS using BrAPI
### Description

Hi team!

Using the Fieldbook App V6.2.5, an error appear:
"ERROR: Response number of observations different..."

Image

The data are being sent to BMS, and it is available to be accepted or discarded.

Cheers,
Julian

### Expected behavior

Data is exported with no errors.

### Field Book version

6.2.5

### PR DESCRIPTION
**Pull request by chaneylc**
### Description

Database refactoring, removing 'name' usage of traits and studies, replacing the usage with db ids.

Closes #471 
Closes #1281 
Closes #914 
Closes #981

### Change Type

- [ ] **`ADDITION`** (non-breaking change that adds functionality)
- [ ] **`CHANGE`** (fix or feature that alters existing functionality)
- [ ] **`FIX`** (non-breaking change that resolves an issue)
- [x] **`OTHER`** (use only for changes like tooling, build system, CI, docs, etc.)

### Release Note

```release-note

```
___

### Release Type

_For internal use - please leave these unchecked unless you are the one completing the merge._

- [ ] **`MAJOR`**
- [ ] **`MINOR`**
- [ ] **`WAIT`** (No immediate release, but the changelog will be still be updated if there is a release note.)

### CODE REVIEW

File: app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt [hunk 1]
```diff
@@ -168,24 +160,33 @@ class TraitBoxView : ConstraintLayout {
...
-                .toString()
-        )
+        if (currentTrait != null) {
+            // Update last used trait so it is preserved when entry moves
+            controller.getPreferences().edit {
+                putString(
+                    GeneralKeys.LAST_USED_TRAIT,
+                    currentTrait!!.id
+                )
+            }
```
Comment (kamathprasad9) [inline app/src/main/java/com/fieldbook/tracker/views/TraitBoxView.kt:195]: We probably should be using null safe operator ?. instead of !!.

**Review by kamathprasad9 — CHANGES_REQUESTED** [review]
Got this crash while opening CollectActivity for a field having gnss observation
OUADao                   D  getAllNames: SELECT DISTINCT A.observation_unit_attribute_name
                            FROM observation_units_attributes AS A
                            JOIN observation_units_values AS V 
                                ON A.internal_id_observation_unit_attribute = V.observation_unit_attribute_db_id
                            WHERE V.study_id = ?
                            ORDER BY A.observation_unit_attribute_name
SQLiteLog                E  (1) no such column:  in "SELECT `` 
                            FROM ObservationUnitProperty 
                            WHERE `plot_id` = ? 
                            LIMIT 1"
AndroidRuntime           D  Shutting down VM
AndroidRuntime           E  FATAL EXCEPTION: main (Ask Gemini)
                            Process: com.fieldbook.tracker.debug, PID: 3703
                            android.database.sqlite.SQLiteException: no such column:  (code 1 SQLITE_ERROR): , while compiling: SELECT `` 
                            FROM ObservationUnitProperty 
                            WHERE `plot_id` = ? 
                            LIMIT 1
                            	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                            	at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
                            	at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1572)
                            	at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1109)
                            	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1137)
                            	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:697)
                            	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:625)
                            	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
                            	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                            	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
                            	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1849)
                            	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1781)
                            	at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion.getObservationUnitPropertyValues$lambda$6(ObservationUnitPropertyDao.kt:78)
                            	at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion.$r8$lambda$Ql__DRaC9isUsSOZGFq5KH1M6Uw(Unknown Source:0)
                            	at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
                            	at com.fieldbook.tracker.database.SqlUtilKt.withDatabase(SqlUtil.kt:166)
                            	at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion.getObservationUnitPropertyValues(ObservationUnitPropertyDao.kt:74)
                            	at com.fieldbook.tracker.database.DataHelper.getObservationUnitPropertyValues(DataHelper.java:781)
                            	at com.fieldbook.tracker.activities.CollectActivity.queryForLabelValue(CollectActivity.java:2622)
                            	at com.fieldbook.tracker.utilities.GeoNavHelper.getPopupInfo(GeoNavHelper.kt:710)
                            	at com.fieldbook.tracker.utilities.GeoNavHelper.runImpactZoneAlgorithm$lambda$14$lambda$13(GeoNavHelper.kt:643)
                            	at com.fieldbook.tracker.utilities.GeoNavHelper.$r8$lambda$YNi8NHlu2kK7GQSvezQiPkNgV7c(Unknown Source:0)
                            	at com.fieldbook.tracker.utilities.GeoNavHelper$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
                            	at android.os.Handler.handleCallback(Handler.java:995)
                            	at android.os.Handler.dispatchMessage(Handler.java:103)
                            	at android.os.Looper.dispatchMessage(Looper.java:315)
                            	at android.os.Looper.loopOnce(Looper.java:251)
                            	at android.os.Looper.loop(Looper.java:349)
                            	at android.app.ActivityThread.main(ActivityThread.java:9200)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)

**Review by kamathprasad9 — CHANGES_REQUESTED** [review]
Field creator allows having duplicate field names - we also might want the FieldDetailFragment to allow duplication
