### PR TITLE
Fix trait bar resizing

### LINKED ISSUE #1200: Navigating back and forth between traits activity and Collect activity messes up sizing for the traits indicator
When navigating to Collect, the traits indicator box size is reset, but when navigating within Collect to other screens like traits and adjusting the traits enabled, the indicator box size is not reset and ends up with smaller/larger/mixed boxes. I think the reset size code needs called in onResume.

### PR DESCRIPTION
**Pull request by kamathprasad9**
### Description
Closes #1200 

### Change Type

- [ ] **`ADDITION`** (non-breaking change that adds functionality)
- [ ] **`CHANGE`** (fix or feature that alters existing functionality)
- [x] **`FIX`** (non-breaking change that resolves an issue)
- [ ] **`OTHER`** (use only for changes like tooling, build system, CI, docs, etc.)

### Release Note

```release-note
Trait indicator icons in Collect now resize as expected
```
___

### Release Type

_For internal use - please leave these unchecked unless you are the one completing the merge._

- [ ] **`MAJOR`**
- [ ] **`MINOR`**
- [ ] **`WAIT`** (No immediate release, but the changelog will be still be updated if there is a release note.)

### CODE REVIEW

File: app/src/main/java/com/fieldbook/tracker/adapters/TraitsStatusAdapter.kt [hunk 1]
```diff
@@ -73,33 +76,40 @@ class TraitsStatusAdapter(private val traitBoxView: TraitBoxView) :
...
+            context.resources.getDimension(R.dimen.fb_trait_status_bar_icon_default_max_size_tablet_screen)
+        } else { // small screens
+            context.resources.getDimension(R.dimen.fb_trait_status_bar_icon_default_max_size)
+        }
+        TypedValue.applyDimension(
+            TypedValue.COMPLEX_UNIT_DIP,
+            defaultMaxSizeDp,
+            context.resources.displayMetrics
+        ).toInt() // in px
+    }
```
Comment (chaneylc) [inline app/src/main/java/com/fieldbook/tracker/adapters/TraitsStatusAdapter.kt:93]: You should be able to provide alternative resources for device types instead of needing that dpi threshold check, which can lead to false tablet recognition:

https://developer.android.com/guide/topics/resources/providing-resources

**Review by chaneylc — CHANGES_REQUESTED** [review]
