### PR TITLE
Brapi url preference fixes

### LINKED ISSUE #485: [BUG] Different page was displayed after authorizing while OAuth2 Implicit Grant was selected
**Describe the bug**
The user is always redirected to BRAPI Test Server ([auth.brapi.org](http://auth.brapi.org/)) when use 'OAuth2 Implicit Grant' as OIDC Flow.

**To Reproduce**
1. Go to Settings -> BrAPI 
2. Tap OIDC Flow and then select OAuth2 Implicit Grant.
3. Tap Base URL and enter a base url
4. Tap Save and Authorize

**Expected behavior**
User should see the login page set as the base URL

**Device Info (please complete the following information):**
 - Model: Pixel 2
 - OS: Android 28
 - Field Book Version: v5.2
 - 
**Additional context**
I guess the problem lies in this line: https://github.com/PhenoApps/Field-Book/blob/develop/app/src/main/java/com/fieldbook/tracker/activities/BrapiAuthActivity.java#L118.

### PR DESCRIPTION
**Pull request by chaneylc**
Fixes #485

### CODE REVIEW

File: app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java [hunk 1]
```diff
@@ -410,4 +301,177 @@ public void onDisplayPreferenceDialog(Preference preference) {
...
+            startActivity(intent);
+        }
+    }
+
+    //checks the uri scheme, uris without http/https causes auth to crash
+    private void brapiAuth() {
+
+        if (brapiOIDCURLPreference.getText().contains("http://")
+            || brapiURLPreference.getText().contains("http://")) {
+
```
Comment (BrapiCoordinatorSelby) [inline app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java:335]: maybe should be `startsWith()` instead of `contains()`

File: app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java [hunk 2]
```diff
@@ -180,73 +160,60 @@ public void onResume() {
...
+            setOidcFlowUi();
+        }
+
+        return true;
     }
 
     @Override
     public boolean onPreferenceTreeClick(Preference preference) {
         switch (preference.getKey()){
             case "brapi_server_cassavabase":
```
Comment (BrapiCoordinatorSelby) [inline app/src/main/java/com/fieldbook/tracker/preferences/BrapiPreferencesFragment.java:191]: Please make sure any changes here don't overwrite any existing fixes for #398

**Review by BrapiCoordinatorSelby — APPROVED** [review]
I left a couple of small comments, overall looks good

**Comment by chaneylc** [comment]
Thanks @BrapiCoordinatorSelby I will make these changes
